spring:
    application:
        name: pitchain
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: ''
        url: jdbc:mysql://localhost:3306/pitchain
        username: root
    jpa:
        hibernate:
            ddl-auto: update

logging:
    level:
        org:
            hibernate:
                SQL: DEBUG
                orm:
                    jdbc:
                        bind: TRACE